# Generated by Django 4.0.4 on 2022-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a atx jeans premium product', max_length=200),
            preserve_default=False,
        ),
    ]
